import os
import subprocess

def generate_beamer_tex(output_filename="acceptance_presentation.tex"):
    """Generates a LaTeX Beamer .tex file for the acceptance comparisons."""
    
    tex_content = r"""\documentclass[aspectratio=169]{beamer}
\usetheme{Madrid}
\usecolortheme{default}

\usepackage{graphicx}
\usepackage{caption}

% Set title and author
\title{Acceptance Discrepancy Investigation}
\subtitle{Comparing E906 Acceptance Calculations}
\author{Chatura Kuruppu}
\institute{Fermilab / NMSU}
\date{\today}

\begin{document}

% Title Slide
\begin{frame}
    \titlepage
\end{frame}

% Slide 1: Initial Discrepancy Overview
\begin{frame}{Initial Discrepancy: Overall Acceptance}
    \begin{columns}
        \column{0.5\textwidth}
        \centering
        \textbf{Chatura's Acceptance} \\
        \vspace{0.2cm}
        % Adjust the path or extension if necessary
        \includegraphics[width=0.95\textwidth]{acceptance_mass_chatura.png}
        
        \column{0.5\textwidth}
        \centering
        \textbf{Kenichi's Acceptance} \\
        \vspace{0.2cm}
        % Adjust the path or extension if necessary
        \includegraphics[width=0.95\textwidth]{acceptance_mass_kenichi.png}
    \end{columns}
    \vspace{0.5cm}
    \begin{itemize}
        \item Comparing the newly calculated acceptance to Kenichi's recent ROOT files.
        \item Next slides breakdown the discrepancy by $x_F$ bins (Hugo vs. No D1 Cut vs. With D1 Cut).
    \end{itemize}
\end{frame}
"""

    # Loop to generate a slide for each of the 16 xF bins
    for i in range(16):
        # Paths to the PDFs generated by your previous ROOT script
        path_lh2 = f"acceptance_comparisons/compare_LH2_xFbin{i}.pdf"
        path_ld2 = f"acceptance_comparisons/compare_LD2_xFbin{i}.pdf"
        
        slide = f"""
% Slide for xF bin {i}
\\begin{{frame}}{{Acceptance Comparison: $x_F$ Bin {i}}}
    \\begin{{columns}}
        \\column{{0.5\\textwidth}}
        \\centering
        \\textbf{{LH2 Target}} \\\\
        \\includegraphics[width=\\textwidth]{{{path_lh2}}}
        
        \\column{{0.5\\textwidth}}
        \\centering
        \\textbf{{LD2 Target}} \\\\
        \\includegraphics[width=\\textwidth]{{{path_ld2}}}
    \\end{{columns}}
\\end{{frame}}
"""
        tex_content += slide

    # End the LaTeX document
    tex_content += r"\end{document}"

    # Write the content to the .tex file
    with open(output_filename, 'w') as f:
        f.write(tex_content)
    
    print(f"Successfully generated {output_filename}")

def compile_latex(filename):
    """Compiles the LaTeX file using pdflatex."""
    print(f"Compiling {filename} with pdflatex...")
    try:
        # Run pdflatex twice to ensure formatting and references are fully resolved
        subprocess.run(["pdflatex", "-interaction=nonstopmode", filename], check=True, stdout=subprocess.DEVNULL)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", filename], check=True, stdout=subprocess.DEVNULL)
        
        pdf_name = filename.replace('.tex', '.pdf')
        print(f"\nCompilation successful! Presentation saved as '{pdf_name}'")
    except subprocess.CalledProcessError:
        print("\nError: pdflatex compilation failed. You may need to compile it manually or check if pdflatex is installed.")
    except FileNotFoundError:
        print("\nError: pdflatex command not found. Please install a LaTeX distribution (like TeX Live) or compile the .tex file manually.")

if __name__ == "__main__":
    tex_file = "acceptance_presentation.tex"
    generate_beamer_tex(tex_file)
    compile_latex(tex_file)