#!/bin/bash
# Script to generate and compile Beamer slides for Roadset Systematics

TEX_FILE="roadset_systematics.tex"
PDF_FILE="roadset_systematics.pdf"

echo "================================================="
echo " Building Roadset Systematics Presentation"
echo "================================================="

# 1. Run the Python script to generate the .tex file
echo "--> Running generate_beamer.py..."
python3 generate_beamer.py

# Check if the .tex file was created successfully
if [ ! -f "$TEX_FILE" ]; then
    echo "ERROR: $TEX_FILE was not generated. Check Python script."
    exit 1
fi

# 2. Compile the LaTeX file (Running twice is standard for Beamer/LaTeX formatting)
echo "--> Compiling with pdflatex (Pass 1)..."
pdflatex -interaction=nonstopmode "$TEX_FILE" > /dev/null

echo "--> Compiling with pdflatex (Pass 2)..."
pdflatex -interaction=nonstopmode "$TEX_FILE" > /dev/null

# Check if PDF was generated successfully
if [ -f "$PDF_FILE" ]; then
    echo "================================================="
    echo " ✔ Success! Presentation compiled: $PDF_FILE"
    echo "================================================="
    
    # 3. Clean up auxiliary files generated by LaTeX
    echo "--> Cleaning up auxiliary files..."
    rm -f *.aux *.log *.nav *.out *.snm *.toc
else
    echo "ERROR: Compilation failed. Check LaTeX syntax."
    exit 1
fi